version: '2'
services:
    sistemaswebapp-app:
        image: sistemaswebapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sistemaswebapp-postgresql:5432/sistemaswebapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sistemaswebapp-postgresql:
        extends:
            file: postgresql.yml
            service: sistemaswebapp-postgresql
